// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volvo_API.Repository.Context;

namespace Volvo_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210904131620_InitialSeed")]
    partial class InitialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Volvo_API.Models.Truck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FabricationYear")
                        .HasColumnType("int");

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FabricationYear = 2021,
                            ModelId = 1L,
                            ModelYear = 2021
                        },
                        new
                        {
                            Id = 2L,
                            FabricationYear = 2021,
                            ModelId = 1L,
                            ModelYear = 2022
                        },
                        new
                        {
                            Id = 3L,
                            FabricationYear = 2021,
                            ModelId = 2L,
                            ModelYear = 2021
                        });
                });

            modelBuilder.Entity("Volvo_API.Models.TruckModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TruckModels");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Model = "FH"
                        },
                        new
                        {
                            Id = 2L,
                            Model = "FM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
